// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1E3pC4cAODWPFXeBvDYfwDK2oB6sSAg8',
    appId: '1:134539616382:web:f2d423d3ede71837a3782f',
    messagingSenderId: '134539616382',
    projectId: 'on-time-meds',
    authDomain: 'on-time-meds.firebaseapp.com',
    storageBucket: 'on-time-meds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoIsvfd20Cz8fzVAQmvd739Ao0OAY8-1g',
    appId: '1:134539616382:android:5ec83cf5a41aedefa3782f',
    messagingSenderId: '134539616382',
    projectId: 'on-time-meds',
    storageBucket: 'on-time-meds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD0EYtCxoqGJYRKH1tb1nKyDSY6-Dom2k',
    appId: '1:134539616382:ios:17b2f54d74e5f198a3782f',
    messagingSenderId: '134539616382',
    projectId: 'on-time-meds',
    storageBucket: 'on-time-meds.firebasestorage.app',
    iosBundleId: 'com.example.onTimeMeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD0EYtCxoqGJYRKH1tb1nKyDSY6-Dom2k',
    appId: '1:134539616382:ios:17b2f54d74e5f198a3782f',
    messagingSenderId: '134539616382',
    projectId: 'on-time-meds',
    storageBucket: 'on-time-meds.firebasestorage.app',
    iosBundleId: 'com.example.onTimeMeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1E3pC4cAODWPFXeBvDYfwDK2oB6sSAg8',
    appId: '1:134539616382:web:88a2e60abecc3dc8a3782f',
    messagingSenderId: '134539616382',
    projectId: 'on-time-meds',
    authDomain: 'on-time-meds.firebaseapp.com',
    storageBucket: 'on-time-meds.firebasestorage.app',
  );

}